---
sudo: required
dist: bionic
notifications:
  slack:
    on_failure: always
matrix:
  fast_finish: true
  include:

    # https://github.com/anchore/anchore-engine
    # https://docs.anchore.com/current/docs/engine/quickstart/
    - name: "scan images w Anchore Engine w docker-compose wo snaps on bionic amd64"
      dist: bionic
      arch: amd64
      services:
        - docker      
      language: python
      # python: 3.7
      before_install:
        - pip3 install virtualenv
        - virtualenv -p $(which python3) ~venvpy3
        - source ~venvpy3/bin/activate
        - pip install -r requirements.txt
      script:
        #  Download the docker-compose.yaml file and start
        - curl https://docs.anchore.com/current/docs/engine/quickstart/docker-compose.yaml > docker-compose.yaml
        - docker-compose up -d
        # Verify service availability
        - docker-compose ps
        # get the status of the Anchore Engine services
        - docker-compose exec api anchore-cli system status
        # check the status of the feed sync using the CLI
        - docker-compose exec api anchore-cli system feeds list
        # he CLI tool includes a useful utility that will block until the feeds have completed a successful sync
        - docker-compose exec api anchore-cli system wait
        #  adding a container image for analysis
        - docker-compose exec api anchore-cli image add docker.io/library/debian:7
        # waiting for the analysis to complete
        - docker-compose exec api anchore-cli image wait docker.io/library/debian:7
        # running content reports
        - docker-compose exec api anchore-cli image content docker.io/library/debian:7 os
      after_success:
        - deactivate        

# https://docs.anchore.com/current/docs/installation/anchore_cli/
    - name: "Installing Anchore CLI on Debian and Ubuntu wo snaps on bionic amd64"
      dist: bionic
      arch: amd64
      services:
        - docker      
      language: python
      # python: 3.7
      before_install:
        - pip3 install virtualenv
        - virtualenv -p $(which python3) ~venvpy3
        - source ~venvpy3/bin/activate
        - pip install -r requirements.txt
      script:
        - sudo apt-get update -qq
        - sudo apt-get install -qqy python-pip
        - pip install --user --upgrade anchorecli
      after_success:
        - deactivate 

# https://docs.anchore.com/current/docs/installation/anchore_cli/
    - name: "Installing the Anchore CLI from source wo snaps on bionic amd64"
      dist: bionic
      arch: amd64
      services:
        - docker      
      language: python
      # python: 3.7
      before_install:
        - pip3 install virtualenv
        - virtualenv -p $(which python3) ~venvpy3
        - source ~venvpy3/bin/activate
        - pip install -r requirements.txt
      script:
        - git clone https://github.com/anchore/anchore-cli
        - cd anchore-cli
        - pip install --user --upgrade
      after_success:
        - deactivate        

    - name: "Installing Anchore CLI w homebrew on macOS 10.15.7 osx xcode12.2"
      os: osx
      osx_image:
        - xcode12.2 #macOS 10.15.7
      addons:
        homebrew:
          packages:
          - python
          - git
          update: true
      language: shell
      before_install:
        - pip3 install virtualenv
        - virtualenv -p $(which python3) ~venvpy3
        - source ~venvpy3/bin/activate
        - python --version
        - pip install -r requirements.txt
      script:
      - pip install --user --upgrade anchorecli
      after_success:
        - deactivate        